<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="7.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\IronBridge.Shared\IronBridge.Shared.csproj" />
    <ProjectReference Include="..\Product.Repository\Product.Repository.csproj" />
  </ItemGroup>

</Project>
